name: "Tree-sitter fact dump"
description: "Emit code_facts_full.json and code_facts_delta.json"

inputs:
  out_full:  { required: true }
  out_delta: { required: true }
  base_sha:  { required: true }

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install compatible Tree-sitter wheels
      shell: bash
      run: |
        pip install --no-cache-dir \
          tree_sitter==0.20.4 \
          tree-sitter-languages==1.10.2

    - name: Generate code facts
      shell: bash
      run: |
        python "${{ github.action_path }}/extractor.py" \
          --out-full   "${{ inputs.out_full }}" \
          --out-delta  "${{ inputs.out_delta }}" \
          --base-sha   "${{ inputs.base_sha }}"
