name: "Tree-sitter fact dump"
description: "Emit code_facts_full.json (all symbols) and code_facts_delta.json (changed files)"
author: "Joseph Folkes"
branding: { icon: archive, color: purple }

inputs:
  out_full:  { description: "Path for the full JSON output",  required: true }
  out_delta: { description: "Path for the delta JSON output", required: true }
  base_sha:  { description: "Commit SHA to diff against",     required: true }

runs:
  using: "composite"
  steps:
    # 1  Python runtime
    - uses: actions/setup-python@v5
      with: { python-version: "3.12" }

    # 2  Install bindings **and** pre-built grammars (no compilation needed)
    - name: Install Tree-sitter Python packages
      shell: bash
      run: |
        pip install --no-cache-dir \
          "tree_sitter>=0.25,<0.26" \
          "tree-sitter-languages>=1.9,<2"

    # 3  Run the extractor
    - name: Dump code facts (full + delta)
      shell: bash
      run: |
        python "${{ github.action_path }}/extractor.py" \
          --out-full   "${{ inputs.out_full }}" \
          --out-delta  "${{ inputs.out_delta }}" \
          --base-sha   "${{ inputs.base_sha }}"
